name: Publish to store

on:
  push:
    tags:        
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Pushes to another repository folder
        uses: NoahDragon/action-push-repo-as-subdirectory-in-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          dest-repo: 'Sparclex/raycast-extensions'
          dest-folder: 'extensions/hakuna'
          commit-message: 'Hakuna Release ${{ env.RELEASE_VERSION }}'
